aliyun-oss:
    endpoint: yourEndpoint
    access-key-id: yourAccessKeyId
    access-key-secret: yourAccessKeySecret
    bucket-name: yourBucketName
    bucket-url: yourBucketUrl
    base-path: yourBasePath
autocode:
    server-model: /model/%s
    server-router: /router/%s
    server: /server
    server-api: /api/v1/%s
    server-plug: /plugin/%s
    server-initialize: /initialize
    root: /webser/app
    web-table: /view
    web: /web/src
    server-service: /service/%s
    server-request: /model/%s/request/
    web-api: /api
    web-form: /view
    transfer-restart: true
aws-s3:
    bucket: xx
    region: xx
    endpoint: ""
    secret-id: your-secret-id
    secret-key: your-secret-key
    base-url: https://xx
    path-prefix: gin-api-tpl
    s3-force-path-style: false
    disable-ssl: false
captcha:
    key-long: 6
    img-width: 240
    img-height: 80
    open-captcha: 0
    open-captcha-timeout: 3600
cors:
    mode: strict-whitelist
    whitelist:
        - allow-origin: example1.com
          allow-methods: POST, GET
          allow-headers: Content-Type,AccessToken,X-CSRF-Token, Authorization, Token,X-Token,X-User-Id
          expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type
          allow-credentials: true
        - allow-origin: example2.com
          allow-methods: GET, POST
          allow-headers: content-type
          expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type
          allow-credentials: true
db-list:
    - type: "mysql"
      alias-name: "test-2"
      prefix: ""
      port: "3307"
      config: charset=utf8mb4&parseTime=True&loc=Local
      db-name: "gin-api-tpl"
      username: "gin-api-tpl"
      password: "44ff6eeebc0111e8fe7cd59146ea40f0^A"
      path: "10.0.44.83"
      engine: ""
      log-mode: ""
      max-idle-conns: 10
      max-open-conns: 100
      singular: false
      log-zap: false
      disable: true
email:
    to: xxx@qq.com
    from: xxx@163.com
    host: smtp.163.com
    secret: xxx
    nickname: test
    port: 465
    is-ssl: true
excel:
    dir: ./resource/excel/
hua-wei-obs:
    path: you-path
    bucket: you-bucket
    endpoint: you-endpoint
    access-key: you-access-key
    secret-key: you-secret-key
jwt:
    signing-key: 77u13e90-b8f1-48dd-bfd4-54913edb37a5
    expires-time: 7d
    buffer-time: 1d
    issuer: gin-api-tpl
ldap:
    enable: true
    ldap-server: 1.1.1.1
    ldap-port: 389
    is-ssl: false
    start-tls: false
    ldap-dn: cn=root,dc=sss,dc=com
    ldap-password: 123456
    ldap-ou: dc=sss,dc=com
    ldap-filter: (&(uid=%s))
    field-mapping: |-
        {
          "userName": "uid",
          "nickName": "cn",
          "email": "mail",
          "phone": "mobile"
        }
    timeout: 30
    pagelimit: 1000
local:
    path: uploads/file
    store-path: uploads/file
mongo:
    coll: ""
    options: ""
    database: ""
    username: admin
    password: ""
    auth-source: ""
    min-pool-size: 0
    max-pool-size: 100
    socket-timeout-ms: 0
    connect-timeout-ms: 0
    is-zap: false
    hosts:
        - host: ""
          port: ""
mssql:
    prefix: ""
    port: ""
    config: ""
    db-name: ""
    username: ""
    password: ""
    path: ""
    engine: ""
    log-mode: ""
    max-idle-conns: 10
    max-open-conns: 100
    singular: false
    log-zap: false
mysql:
    prefix: ""
    port: "3306"
    config: charset=utf8mb4&parseTime=True&loc=Local
    db-name: gin-api-tpl
    username: gin-api-tpl
    password: 123456
    path: 10.0.45.27
    engine: ""
    log-mode: error
    max-idle-conns: 10
    max-open-conns: 100
    singular: false
    log-zap: true
oracle:
    prefix: ""
    port: ""
    config: ""
    db-name: ""
    username: ""
    password: ""
    path: ""
    engine: ""
    log-mode: ""
    max-idle-conns: 10
    max-open-conns: 100
    singular: false
    log-zap: false
pgsql:
    prefix: ""
    port: ""
    config: ""
    db-name: ""
    username: ""
    password: ""
    path: ""
    engine: ""
    log-mode: ""
    max-idle-conns: 10
    max-open-conns: 100
    singular: false
    log-zap: false
qiniu:
    zone: ZoneHuaDong
    bucket: ""
    img-path: ""
    access-key: ""
    secret-key: ""
    use-https: false
    use-cdn-domains: false
redis:
    addr: 127.0.0.1:6379
    password: ""
    db: 0
    useCluster: false
    clusterAddrs:
        - 172.21.0.3:7000
        - 172.21.0.4:7001
        - 172.21.0.2:7002
sqlite:
    prefix: ""
    port: ""
    config: ""
    db-name: ""
    username: ""
    password: ""
    path: ""
    engine: ""
    log-mode: ""
    max-idle-conns: 10
    max-open-conns: 100
    singular: false
    log-zap: false
system:
    db-type: mysql
    oss-type: local
    router-prefix: ""
    addr: 8888
    iplimit-count: 15000
    iplimit-time: 3600
    use-multipoint: false
    use-redis: false
    use-mongo: false
tencent-cos:
    bucket: xx
    region: xx
    secret-id: your-secret-id
    secret-key: your-secret-key
    base-url: https://xx
    path-prefix: gin-api-tpl
zap:
    level: info
    prefix: '[gin-api-tpl]'
    format: console
    director: log
    encode-level: LowercaseColorLevelEncoder
    stacktrace-key: stacktrace
    max-age: 0
    show-line: false
    log-in-console: true
basicauth:
    user: "xxx"
    password: "xxx"
prom:
    host: "http://1.1.1.1:8481/select/0/prometheus"
    user: xx
    auth: xx
target:
    TargetUp: max(max_over_time(target_up{ident=~'(%s)'}[%dm])) by (ident)
    LoadPerCore: max(max_over_time(system_load_norm_1{ident=~'(%s)'}[%dm])) by (ident)
    MemUtil: 100-max(max_over_time(mem_available_percent{ident=~'(%s)'}[%dm])) by (ident)
    DiskUtil: max(max_over_time(disk_used_percent{ident=~"(%s)", path="/"}[%dm])) by (ident)
n9e_adm:
    - 用户1
    - 用户2